export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const GET_MOVIES_LIST = "GET_MOVIES_LIST";
export const SET_ERROR_UPON_FAILURE = "SET_ERROR_UPON_FAILURE";
export const GET_SEARCHED_MOVIE = "GET_SEARCHED_MOVIE";
export const MOVIE_DETAIL_DATA = "MOVIE_DETAIL_DATA";
